### PR TITLE
Completing exitcodes

### LINKED ISSUE #21: Proper exit code
@kinafu I see you already did some stuff in https://github.com/kinafu/borg-cron-helper/commit/835af05e81b585bc88d81a162c930abe6f6638b6.

Do you want to do it (in a new branch) here as well?

Features should be:
* exit with highest exit code, when some borg commands fail
* the thing is called "exit code" on Linux, so please use this term (in your variables, etc.)
* skipping prune when borg exited with exit code "2" is a good idea, you can include it here, too (for future changes maybe use a variable `skipprune` or similar, which is set independently from the exit code, as we may introduce further conditions, where prune should be skipped)
* do not forget to also handle the exit code in `borgcron_starter.sh`

### PR DESCRIPTION
**Pull request by kinafu**
All of the underneath is intended to resolve #21.
- complete exitcodes in **borgcron_starter.sh**
To trigger "chronic", an exit code needs to be set. Directing sth. to stderr does not trigger chronic.

- add exitcode "tracking" in **borgcron.sh**
- edit final message, indicating successful / unsuccessful backup

### CODE REVIEW

File: borgcron.sh [hunk 1]
```diff
@@ -78,6 +78,13 @@ rm_lock() {
 	rm "$RUN_PID_DIR/BORG_$BACKUP_NAME.pid"
 }
 
+track_exitcode() {
+	EXITCODE_TEMP="$1"
```
Comment (rugk) [inline borgcron.sh]: Variables not being constants, should be written in lower letters here, please. (also applies to `EXITCODE`)

Comment (rugk) [reply borgcron.sh]: Wait, actually you do not need this temp variable anyway, so löeave them away, use "$1" directly, when needed.

File: borgcron.sh [hunk 2]
```diff
@@ -173,7 +182,8 @@ for i in $( seq "$REPEAT_NUM" ); do
 
 	# add local lock
 	do_lock
-
+	track_exitcode "$?"
```
Comment (rugk) [inline borgcron.sh]: You do this to check the exit code of `do_lock`? That's not necessary, `do_lock` will force an exit if it really fails and cannot lock (for safety reasons), so you can remove this line.

File: borgcron.sh [hunk 3]
```diff
@@ -183,14 +193,16 @@ for i in $( seq "$REPEAT_NUM" ); do
 		$BACKUP_DIRS
 
 	# check return code
-	errorcode="$?"
+	EXITCODE_BORGBACKUP="$?"
```
Comment (rugk) [inline borgcron.sh]: Lower case, again…

File: borgcron.sh [hunk 4]
```diff
@@ -216,15 +228,15 @@ for i in $( seq "$REPEAT_NUM" ); do
 			info_log "Borg has been successful."
 			;;
 		* )
-			error_log "Unknown error with code ${errorcode} happened."
+			error_log "Unknown error with code "$EXITCODE" happened."
```
Comment (rugk) [inline borgcron.sh]: Quoting/syntax error, see shellcheck.

File: borgcron.sh [hunk 5]
```diff
@@ -216,15 +228,15 @@ for i in $( seq "$REPEAT_NUM" ); do
...
 			;;
 	esac
 
 	# optional user question
 	guiTryAgain || break;
 
 	# exit on non-critical errors (ignore 1 = warnings)
-	if [ ${errorcode} -le 1 ]; then
+	if [ "$EXITCODE_BORGBACKUP" -le 1 ]; then
```
Comment (rugk) [inline borgcron.sh]: Note sure whether the quotes cause trouble here, but in the end it is a number, so quotes are not needed.

File: borgcron.sh [hunk 6]
```diff
@@ -238,19 +250,27 @@ done
...
 
-if [ "$PRUNE_PARAMS" ] && [ "$PRUNE_PREFIX" != "null" ]; then
+if [ "$PRUNE_PARAMS" ] && [ "$PRUNE_PREFIX" != "null" ] && [ "$EXITCODE" -lt 2 ]; then
 	echo "Running prune for $BACKUP_NAME…"
 	do_lock
 	# shellcheck disable=SC2086
 	$BORG_BIN prune -v --list --prefix "$PRUNE_PREFIX" $PRUNE_PARAMS
+	track_exitcode $?
 	rm_lock
+	track_exitcode $?
```
Comment (rugk) [inline borgcron.sh]: Same reason as above, `rm_lock` will exit if needed, this check can be removed.

**Review by rugk — CHANGES_REQUESTED** [review]

**Comment by rugk** [comment]
Thanks for your PR! :+1: BTW, nice idea of using this tiny function to track the exit codes automatically…

I've just commented some lines and please have a look at the unit tests.

File: tests/unitTests/borgcron.sh [hunk 7]
```diff
@@ -286,7 +286,7 @@ testNotRetry(){
 	addFakeBorgCommand 'exit 2'
 
 	# TODO: change to "assertFalse" when exit code is implemented
```
Comment (rugk) [inline tests/unitTests/borgcron.sh]: Yes, that's what you should do, but as you did it now, you can also remove the TODO message.

File: borgcron.sh [hunk 8]
```diff
@@ -250,12 +250,13 @@ done
 # backup-type are touched.
 # ($PRUNE_PARAMS intentionally not quoted)
 
-if [ "$PRUNE_PARAMS" ] && [ "$PRUNE_PREFIX" != "null" ] && [ "$EXITCODE" -lt 2 ]; then
+if [ "$PRUNE_PARAMS" ] && [ "$PRUNE_PREFIX" != "null" ] && [ "$EXITCODE" -lt 1 ]; then
```
Comment (rugk) [inline borgcron.sh]: Wait wait, why not prune if the exit code is "1"? What is the reason behind it?

If the backup fails, because some files may be missing/inaccessible/permission problems/etc. pruning should still be triggered. Otherwise users, who always have some of these "minor" problems, may never get old backups pruned.

File: borgcron.sh (hunk 2 above)
Comment (kinafu) [reply borgcron.sh]: ✅

File: tests/unitTests/borgcron.sh (hunk 7 above)
Comment (kinafu) [reply tests/unitTests/borgcron.sh]: ✅

File: borgcron.sh [hunk 9]
```diff
@@ -79,9 +79,9 @@ rm_lock() {
 }
 
 track_exitcode() {
-	EXITCODE_TEMP="$1"
-	if [ "$EXITCODE_TEMP" -gt "$EXITCODE" ]; then
-		EXITCODE="$EXITCODE_TEMP"
+	exitcode_temp="$1"
+	if [ "$exitcode_temp" -gt "$exitcode" ]; then
```
Comment (rugk) [inline borgcron.sh]: temp still unnecessary

File: borgcron_starter.sh [hunk 10]
```diff
@@ -29,6 +29,14 @@ get_full_path() {
 	fi
 }
```
Comment (rugk) [inline borgcron_starter.sh:29]: This empty line is not necessary.

File: borgcron_starter.sh [hunk 11]
```diff
@@ -57,8 +65,12 @@ case "$1" in
...
 			else
 				echo "The backup settings file \"$configfile.sh\" could not be found." >&2
-				exit 1
+				track_exitcode "$?"
 			fi
 		done
 		;;
 esac
+
+if [ "$exitcode" -gt 0 ]; then
```
Comment (rugk) [inline borgcron_starter.sh]: unnecessary check, if `$exitcode` is 0 then why not do `exit 0`? That's fine. :smiley:

**Review by rugk — CHANGES_REQUESTED** [review]

File: borgcron.sh [hunk 12]
```diff
@@ -216,15 +226,17 @@ for i in $( seq "$REPEAT_NUM" ); do
 			info_log "Borg has been successful."
 			;;
 		* )
-			error_log "Unknown error with code ${errorcode} happened."
+			error_log "Unknown error with code $exitcode happened."
 			;;
 	esac
-
+if [ "$exitcode_borgbackup" -gt "$exitcode" ]; then
```
Comment (rugk) [inline borgcron.sh]: wrong indentation

File: borgcron.sh [hunk 13]
```diff
@@ -173,7 +182,7 @@ for i in $( seq "$REPEAT_NUM" ); do
 
 	# add local lock
 	do_lock
-
+
```
Comment (rugk) [inline borgcron.sh]: Huh? 😯 (But it is okay, my IDE would delete this anyway when editing it the next time… :laughing:)

**Review by rugk — CHANGES_REQUESTED** [review]

File: borgcron.sh (hunk 13 above)
Comment (kinafu) [reply borgcron.sh]: 👍

**Review by rugk — APPROVED** [review]
